language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t angusbean/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true angusbean/docker-react npm run test
